# Sync Fork workflow
# This workflow fetches updates from the Klipper3d/klipper upstream repo
# and applies them to this fork, excluding the .github directory to
# preserve custom workflows.

name: Sync Fork

on:
  schedule:
    - cron: "0 0 * * *" # Run daily at midnight UTC
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Fork
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set Git User
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Add Upstream Remote
        run: git remote add upstream https://github.com/Klipper3d/klipper.git

      - name: Fetch Upstream
        run: git fetch upstream

      - name: Hard Reset to Upstream
        run: |
          git reset --hard upstream/master
          git restore --source=origin/master .github
          git add .github
          if ! git diff --cached --quiet; then
            echo "ci(workflows): replace upstream GitHub Actions with fork-specific sync job
            Removed all inherited workflows from the upstream Klipper repo to prevent
            them from running on this fork. Added a custom workflow that pulls upstream
            changes nightly while excluding the .github directory to preserve custom CI.
            
            This allows the fork to stay up-to-date with the main project codebase while
            retaining separate automation behavior, useful for bypassing hardcoded
            repository logic in external tooling." > commit-message.txt
            git commit -F commit-message.txt
          else
            echo "No changes in .github to commit"
          fi

      - name: Push Only If There Are Changes
        run: |
          if [ "$(git rev-parse HEAD)" != "$(git rev-parse origin/master)" ]; then
            git push origin master --force
          else
            echo "Nothing new to push"
          fi
